In [90]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [91]:
df=pd.read_csv('../DataSets/Malware.csv')
df

hash  millisecond  \
0      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            0   
1      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            1   
2      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            2   
3      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            3   
4      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            4   
...                                                  ...          ...   
99995  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          995   
99996  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          996   
99997  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          997   
99998  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          998   
99999  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          999   

      classification  state  usage_counter        prio  static_prio  \
0            malware      0              0  3069378560        14274   
1            malware      0              0  3069378560        14274   
2            malware      0              0  3069378560        14274   
3            malware      0              0  3069378560        14274   
4            malware      0              0  3069378560        14274   
...              ...    ...            ...         ...          ...   
99995        malware   4096              0  3070148608        13988   
99996        malware   4096              0  3070148608        13988   
99997        malware   4096              0  3070148608        13988   
99998        malware   4096              0  3070148608        13988   
99999        malware   4096              0  3070148608        13988   

       normal_prio  policy  vm_pgoff  ...  nivcsw  min_flt  maj_flt  \
0                0       0         0  ...       0        0      120   
1                0       0         0  ...       0        0      120   
2                0       0         0  ...       0        0      120   
3                0       0         0  ...       0        0      120   
4                0       0         0  ...       0        0      120   
...            ...     ...       ...  ...     ...      ...      ...   
99995            0       0         0  ...       2        1      120   
99996            0       0         0  ...       2        1      120   
99997            0       0         0  ...       2        1      120   
99998            0       0         0  ...       2        1      120   
99999            0       0         0  ...       2        1      120   

       fs_excl_counter        lock   utime  stime  gtime  cgtime  signal_nvcsw  
0                    0  3204448256  380690      4      0       0             0  
1                    0  3204448256  380690      4      0       0             0  
2                    0  3204448256  380690      4      0       0             0  
3                    0  3204448256  380690      4      0       0             0  
4                    0  3204448256  380690      4      0       0             0  
...                ...         ...     ...    ...    ...     ...           ...  
99995                0  3204448256  371979      3      0       0             0  
99996                0  3204448256  371979      3      0       0             0  
99997                0  3204448256  371979      3      0       0             0  
99998                0  3204448256  371979      3      0       0             0  
99999                0  3204448256  371979      3      0       0             0  

[100000 rows x 35 columns]

In [92]:
df.columns

Index(['hash', 'millisecond', 'classification', 'state', 'usage_counter',
       'prio', 'static_prio', 'normal_prio', 'policy', 'vm_pgoff',
       'vm_truncate_count', 'task_size', 'cached_hole_size', 'free_area_cache',
       'mm_users', 'map_count', 'hiwater_rss', 'total_vm', 'shared_vm',
       'exec_vm', 'reserved_vm', 'nr_ptes', 'end_data', 'last_interval',
       'nvcsw', 'nivcsw', 'min_flt', 'maj_flt', 'fs_excl_counter', 'lock',
       'utime', 'stime', 'gtime', 'cgtime', 'signal_nvcsw'],
      dtype='object')

In [93]:
df.dtypes

hash                 object
millisecond           int64
classification       object
state                 int64
usage_counter         int64
prio                  int64
static_prio           int64
normal_prio           int64
policy                int64
vm_pgoff              int64
vm_truncate_count     int64
task_size             int64
cached_hole_size      int64
free_area_cache       int64
mm_users              int64
map_count             int64
hiwater_rss           int64
total_vm              int64
shared_vm             int64
exec_vm               int64
reserved_vm           int64
nr_ptes               int64
end_data              int64
last_interval         int64
nvcsw                 int64
nivcsw                int64
min_flt               int64
maj_flt               int64
fs_excl_counter       int64
lock                  int64
utime                 int64
stime                 int64
gtime                 int64
cgtime                int64
signal_nvcsw          int64
dtype: object

In [94]:
dt=df.drop('hash',axis=1)

In [95]:
dt

millisecond classification  state  usage_counter        prio  \
0                0        malware      0              0  3069378560   
1                1        malware      0              0  3069378560   
2                2        malware      0              0  3069378560   
3                3        malware      0              0  3069378560   
4                4        malware      0              0  3069378560   
...            ...            ...    ...            ...         ...   
99995          995        malware   4096              0  3070148608   
99996          996        malware   4096              0  3070148608   
99997          997        malware   4096              0  3070148608   
99998          998        malware   4096              0  3070148608   
99999          999        malware   4096              0  3070148608   

       static_prio  normal_prio  policy  vm_pgoff  vm_truncate_count  ...  \
0            14274            0       0         0              13173  ...   
1            14274            0       0         0              13173  ...   
2            14274            0       0         0              13173  ...   
3            14274            0       0         0              13173  ...   
4            14274            0       0         0              13173  ...   
...            ...          ...     ...       ...                ...  ...   
99995        13988            0       0         0              10406  ...   
99996        13988            0       0         0              10406  ...   
99997        13988            0       0         0              10406  ...   
99998        13988            0       0         0              10406  ...   
99999        13988            0       0         0              10406  ...   

       nivcsw  min_flt  maj_flt  fs_excl_counter        lock   utime  stime  \
0           0        0      120                0  3204448256  380690      4   
1           0        0      120                0  3204448256  380690      4   
2           0        0      120                0  3204448256  380690      4   
3           0        0      120                0  3204448256  380690      4   
4           0        0      120                0  3204448256  380690      4   
...       ...      ...      ...              ...         ...     ...    ...   
99995       2        1      120                0  3204448256  371979      3   
99996       2        1      120                0  3204448256  371979      3   
99997       2        1      120                0  3204448256  371979      3   
99998       2        1      120                0  3204448256  371979      3   
99999       2        1      120                0  3204448256  371979      3   

       gtime  cgtime  signal_nvcsw  
0          0       0             0  
1          0       0             0  
2          0       0             0  
3          0       0             0  
4          0       0             0  
...      ...     ...           ...  
99995      0       0             0  
99996      0       0             0  
99997      0       0             0  
99998      0       0             0  
99999      0       0             0  

[100000 rows x 34 columns]

In [96]:
df.classification.unique()

array(['malware', 'benign'], dtype=object)

In [97]:
df.isnull().sum()

hash                 0
millisecond          0
classification       0
state                0
usage_counter        0
prio                 0
static_prio          0
normal_prio          0
policy               0
vm_pgoff             0
vm_truncate_count    0
task_size            0
cached_hole_size     0
free_area_cache      0
mm_users             0
map_count            0
hiwater_rss          0
total_vm             0
shared_vm            0
exec_vm              0
reserved_vm          0
nr_ptes              0
end_data             0
last_interval        0
nvcsw                0
nivcsw               0
min_flt              0
maj_flt              0
fs_excl_counter      0
lock                 0
utime                0
stime                0
gtime                0
cgtime               0
signal_nvcsw         0
dtype: int64

In [98]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [99]:
dt['classification'] = label.fit_transform(dt['classification'])


In [100]:
dt

millisecond  classification  state  usage_counter        prio  \
0                0               1      0              0  3069378560   
1                1               1      0              0  3069378560   
2                2               1      0              0  3069378560   
3                3               1      0              0  3069378560   
4                4               1      0              0  3069378560   
...            ...             ...    ...            ...         ...   
99995          995               1   4096              0  3070148608   
99996          996               1   4096              0  3070148608   
99997          997               1   4096              0  3070148608   
99998          998               1   4096              0  3070148608   
99999          999               1   4096              0  3070148608   

       static_prio  normal_prio  policy  vm_pgoff  vm_truncate_count  ...  \
0            14274            0       0         0              13173  ...   
1            14274            0       0         0              13173  ...   
2            14274            0       0         0              13173  ...   
3            14274            0       0         0              13173  ...   
4            14274            0       0         0              13173  ...   
...            ...          ...     ...       ...                ...  ...   
99995        13988            0       0         0              10406  ...   
99996        13988            0       0         0              10406  ...   
99997        13988            0       0         0              10406  ...   
99998        13988            0       0         0              10406  ...   
99999        13988            0       0         0              10406  ...   

       nivcsw  min_flt  maj_flt  fs_excl_counter        lock   utime  stime  \
0           0        0      120                0  3204448256  380690      4   
1           0        0      120                0  3204448256  380690      4   
2           0        0      120                0  3204448256  380690      4   
3           0        0      120                0  3204448256  380690      4   
4           0        0      120                0  3204448256  380690      4   
...       ...      ...      ...              ...         ...     ...    ...   
99995       2        1      120                0  3204448256  371979      3   
99996       2        1      120                0  3204448256  371979      3   
99997       2        1      120                0  3204448256  371979      3   
99998       2        1      120                0  3204448256  371979      3   
99999       2        1      120                0  3204448256  371979      3   

       gtime  cgtime  signal_nvcsw  
0          0       0             0  
1          0       0             0  
2          0       0             0  
3          0       0             0  
4          0       0             0  
...      ...     ...           ...  
99995      0       0             0  
99996      0       0             0  
99997      0       0             0  
99998      0       0             0  
99999      0       0             0  

[100000 rows x 34 columns]

In [101]:
dt.classification.unique

<bound method Series.unique of 0        1
1        1
2        1
3        1
4        1
        ..
99995    1
99996    1
99997    1
99998    1
99999    1
Name: classification, Length: 100000, dtype: int32>

In [102]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [103]:
x=dt.drop('classification',axis=1).values
y=dt['classification'].values

In [104]:
x

array([[   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    0,    0,    0],
       ...,
       [ 997, 4096,    0, ...,    0,    0,    0],
       [ 998, 4096,    0, ...,    0,    0,    0],
       [ 999, 4096,    0, ...,    0,    0,    0]], dtype=int64)

In [105]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [106]:
x.shape

(100000, 33)

In [107]:
y.shape

(100000,)

In [108]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [109]:
gbm=GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)
gbm.fit(xtrain,ytrain)

GradientBoostingClassifier(random_state=42)

In [110]:
yp=gbm.predict(xtest)

In [111]:
yp

array([1, 1, 0, ..., 0, 0, 0])

In [113]:
acc=accuracy_score(yp,ytest)

In [114]:
acc

0.9999

In [115]:
acc*100

99.99